name: submit-dev-to-master-pr

on: 
  workflow_dispatch:

jobs:
  submit-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Submit dev -> master PR
        uses: actions/github-script@v4
        with:
          script: |
            github.pulls.create({
              ...context.repo,
              title: "Merge dev to master",
              head: "dev",
              base: "master",
            })

